name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - graphviz
  - pip:
    - numpy
    - pandas
    - keras==2.3.1
    - tensorflow
    - nbgitpuller
    - sphinx-gallery
    - xgboost
    - matplotlib
    - plotly
    - sklearn
    - scipy
    - pydot
    - jupyter-tensorboard
