name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - graphviz
  - pip:
    - numpy
    - pandas
    - keras==2.3.1
    - tensorflow==1.14.0
    - nbgitpuller
    - sphinx-gallery
    - xgboost
    - matplotlib
    - plotly
    - sklearn
    - scipy
    - pydot
    - jupyter-tensorboard
