name: example-environment
channels:
  - conda-forge
dependencies:
  - graphviz
  - pip
  - numpy
  - pandas
  - keras==2.3.1
  - tensorflow
  - nbgitpuller
  - sphinx-gallery
  - xgboost
  - matplotlib
  - plotly
  - sklearn
  - scipy
  - pydot
  - jupyter-tensorboard
